# Generated by Django 5.2.3 on 2025-07-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sync_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Synced', 'Synced'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
    ]
