# Generated by Django 5.2.3 on 2025-07-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_invoice_sync_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sync_status',
        ),
    ]
